### ISSUE TITLE
Can't get docker container to work

### ISSUE THREAD

**Issue by crstrand** [teejo75/mtghs#1]
I've been trying for a while, but it doesn't seem like this container will run on a Raspberry Pi 3B as it currently sits.
It is VERY possible that I'm doing something wrong, but I need help.
Did you run this docker container on a Pi?

**Comment by teejo75** [comment]
I have not tested it on a pi, but will give it a shot a bit later today,
and see if I can get that sorted out for you.

**Comment by teejo75** [comment]
This is a lot more complicated to fix than I thought. The problem is that I went for an easy deployment and used a base image that does not provide for multi-architectures.

In order to fix this, I'm going to have to roll my own image from base python (which DOES support multiarch) and roll in fastapi and uvicorn/gunicorn. This will take a bit of time.

**Comment by crstrand** [comment]
If you're up to the challenge, I would very much appreciate it.
I'm running Klipper/Mainsail on my Pi and have python scripts calling tinytuya to control my power bar, but I'd love it to be integrated into Mailsail like Octoprint has.
I was able to pull an arm7 python container and run some python code on my Pi in a  container, but the rest of it (uvicorn, etc.) was too much for me.

**Comment by teejo75** [comment]
Yep, I'll have a look at it this evening, it shouldn't be too difficult.

**Comment by teejo75** [comment]
Fixed. Pull the latest image and it will now work on a pi3b (or any arm64 devices for that matter).

Since I'm not using gunicorn anymore, just one worker instance of uvicorn runs now, but that shouldn't be a problem for most people and is probably better if someone wanted to run this on a cluster.

**Comment by crstrand** [comment]
As an aside, I can't figure out how to successfully pull a container from ghcr.io.  I can pull from other places like docker.io, etc. but I think there's some personal access token hijinx at play here.

**Comment by teejo75** [comment]
Strange. It’s a publicly available repo. You don’t need credentials to
access this particular image.
I’m not sure if it makes any difference, but i use docker-ce. Podman should
also work.

**Comment by crstrand** [comment]
full disclosure: I'm using Podman.  I'm mad at Docker since they started charging for Docker Desktop for Windows. ;)

**Comment by norin89** [comment]
@crstrand did you manage to run `mtghs` on Raspberry Pi 3B?  I' m running Mainsail on Pi 3B+ and can't manage to run the wizard:
<img width="970" alt="Screenshot 2023-09-23 at 18 13 22" src="https://github.com/teejo75/mtghs/assets/7902324/45e16bd7-e532-4b74-9219-0674dfa984fc">

Is that because Raspberry Pi 3/3+ is ARMv7 not ARM64? // @teejo75

**Comment by teejo75** [comment]
This works on a pi3b+, it is what I used to test it.

`Model           : Raspberry Pi 3 Model B Plus Rev 1.3`

What version of docker are you using?

```
user@host:~/docker/mtghs $ sudo docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:36 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
user@host:~/docker/mtghs $ sudo docker run --rm -it -v ./config:/app/config ghcr.io/teejo75/mtghs /app/tinytuya.sh wizard
Unable to find image 'ghcr.io/teejo75/mtghs:latest' locally
latest: Pulling from teejo75/mtghs
3ae0c06b4d3a: Pull complete 
d0a1460068e4: Pull complete 
ae6e57d0fac3: Pull complete 
20a382ddd20c: Pull complete 
f30418ad94aa: Pull complete 
6f0f12eb4bfa: Pull complete 
df60836efe80: Pull complete 
af47924e8a89: Pull complete 
8d03172fec97: Pull complete 
c8865301bd4c: Pull complete 
Digest: sha256:cd470995e8c42a3004fd0d0470996503edd732168f8a059d95119d2a1a948290
Status: Downloaded newer image for ghcr.io/teejo75/mtghs:latest
TinyTuya Setup Wizard [1.12.9]

    Existing settings:
        API Key=XXXXX
        Secret=XXXXX
        DeviceID=XXXXX
        Region=eu

    Use existing credentials (Y/n): 
```

If anything, I would suspect the version of docker may be the problem?

**Comment by norin89** [comment]
I have same version of Docker, but it says my architecture is `arm` while your is `arm64`. 
```
pi@ender3v2neo:~ $ sudo docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:57 2023
 OS/Arch:           linux/arm
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:57 2023
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Do I need 64-bit OS to be able to run this? I am currently running 32-bit.

**Comment by teejo75** [comment]
Oh, yes. That would be it.

**Comment by teejo75** [comment]
@norin89 I tried to create an arm/v7 image for you, but unfortunately the build choked while trying to compile one of the python cryptographic module dependencies as it did not recognize the arm/v7 platform.

I'm not even sure if you would be able to use the script directly (outside of docker) because of this, but you could give it a try.

**Comment by norin89** [comment]
Hi @teejo75, I configured new Mainsail 64-bit OS today, and everything works flawlessly. Thanks! ✋
